(function(){var $=function(s,r){return(r||document).querySelector(s)},$$=function(s,r){return[].slice.call((r||document).querySelectorAll(s))};
var root=document.documentElement;$(".mode").onclick=function(){var t=root.dataset.theme==="dark"?"light":"dark";root.dataset.theme=t;try{localStorage.setItem("theme",t)}catch(e){}};
var b=$(".burger"),n=$("#nav");b.onclick=function(){var o=n.classList.toggle("open");b.setAttribute("aria-expanded",o)};$$("#nav a").forEach(function(a){a.onclick=function(){n.classList.remove("open")}});
var bar=$("#bar"),tp=$("#top");window.addEventListener("scroll",function(){var h=root.scrollHeight-innerHeight;bar.style.width=(h>0?scrollY/h*100:0)+"%";tp.style.display=scrollY>400?"block":"none"});tp.onclick=function(){scrollTo({top:0})};
if("IntersectionObserver"in window){var io=new IntersectionObserver(function(es){es.forEach(function(e){if(e.isIntersecting){e.target.classList.add("in");io.unobserve(e.target)}})},{threshold:.15});$$(".rv").forEach(function(e){io.observe(e)})}else $$(".rv").forEach(function(e){e.classList.add("in")});
$$("[data-n]").forEach(function(el){var t=+el.dataset.n,i=0,s=setInterval(function(){i+=Math.ceil(t/40);if(i>=t){i=t;clearInterval(s)}el.textContent=i+"+"},30)});
$$("[data-tab]").forEach(function(btn){btn.onclick=function(){$$("[data-tab]").forEach(function(x){x.classList.remove("on")});$$(".panel").forEach(function(p){p.classList.remove("on")});btn.classList.add("on");$("#"+btn.dataset.tab).classList.add("on")}});
$$("[data-f]").forEach(function(btn){btn.onclick=function(){$$("[data-f]").forEach(function(x){x.classList.remove("on")});btn.classList.add("on");$$("#works .card").forEach(function(c){c.style.display=btn.dataset.f==="all"||c.dataset.c===btn.dataset.f?"":"none"})}});
var yr=$("#yr");if(yr)yr.onchange=function(){$$("[data-m]").forEach(function(s){var m=+s.dataset.m;s.textContent=Math.round(yr.checked?m*.8:m).toLocaleString("en-IN")})};
var Q=[["Our Google traffic doubled in four months. Reports were easy to understand.","Sample client, Surat"],["They fixed our site speed and titles, and leads started coming in.","Sample client, Ahmedabad"],["Clear plan, honest advice, no empty promises.","Sample client, Vadodara"]],qi=0,q=$("#q");
function sq(){q.textContent="\u201c"+Q[qi][0]+"\u201d \u2014 "+Q[qi][1]}if(q){sq();$("#prev").onclick=function(){qi=(qi+2)%3;sq()};$("#next").onclick=function(){qi=(qi+1)%3;sq()};setInterval(function(){qi=(qi+1)%3;sq()},7000)}
var f=$("#cf");if(f)f.addEventListener("submit",function(e){var bad=0;$$("input,textarea",f).forEach(function(x){var v=!x.value.trim()||(x.type==="email"&&!/^\S+@\S+\.\S+$/.test(x.value));x.classList.toggle("bad",v);if(v)bad=1});$("#msg").textContent=bad?"Please fill all fields correctly.":"";if(bad)e.preventDefault()});
function cnt(el,out,lo,hi){var v=el.value.length,c=v===0?"":v>=lo&&v<=hi?"ok":"warn";out.className="cnt "+c;out.textContent=v+" characters"+(v&&c==="warn"?" (target "+lo+"-"+hi+")":v?" (good)":"")}
var ti=$("#ti");if(ti){var de=$("#de");ti.oninput=function(){cnt(ti,$("#tc"),50,60)};de.oninput=function(){cnt(de,$("#dc"),100,120)};
var kw=$("#kw"),tx=$("#tx");function kd(){var w=tx.value.trim().split(/\s+/).filter(Boolean).length,k=kw.value.trim().toLowerCase(),c=0;if(k){var re=new RegExp(k.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),"g");c=(tx.value.toLowerCase().match(re)||[]).length}var d=w?(c*(k?k.split(/\s+/).length:1)/w*100):0;$("#kd").textContent=w+" words, keyword found "+c+" times, density "+d.toFixed(2)+"%"}kw.oninput=tx.oninput=kd;
var sl=$("#sl");sl.oninput=function(){$("#so").textContent=sl.value.toLowerCase().replace(/[^a-z0-9\s-]/g,"").trim().replace(/\s+/g,"-").replace(/-+/g,"-")}}
})();